Repository pre-onboarding-12th-team3/pre-onboarding-12th-2-3, pull requests merged in 2023-08, with the labels that each got.

#2 [Feat] 이슈 관련 페이지에서 공유하기 위한 UI component
  package-lock.json
  package.json
  src/components/common/.gitkeep
  src/components/common/Heading.tsx
  src/components/common/MarkdownViewer.tsx
  src/components/common/index.ts
  src/components/domain/.gitkeep
  src/components/domain/issue/IssueInfo.tsx
  src/components/domain/issue/index.ts
  src/types/.gitkeep
  src/types/issue.ts
  src/utils/.gitkeep
  src/utils/getFormatDateString.ts
  src/utils/index.ts
Labels: enhancement

#3 [Feat] api 세팅
  .gitignore
  package-lock.json
  package.json
  src/apis/.gitkeep
  src/apis/index.ts
  src/apis/octokitInstance.ts
  src/apis/octokitService.ts
  src/apis/type.ts
  src/constants/.gitkeep
  src/constants/apiConstants.ts
  src/constants/index.ts
Labels: enhancement

#4 [Feat] 이슈 리스트 페이지 기본 구조 작성
  src/components/domain/issue/EmptyList.tsx
  src/components/domain/issue/IssueList.tsx
  src/components/domain/issue/IssueListItem.tsx
  src/components/domain/issue/index.ts
Labels: enhancement

#5 [Fix] issueNumber 타입 확인 수정
  src/apis/octokitService.ts
Labels: bug

#7 [Feat] 페이지 라우팅 설정
  package-lock.json
  package.json
  src/App.tsx
  src/main.tsx
  src/pages/DetailPage.tsx
  src/pages/ErrorPage.tsx
  src/pages/MainPage.tsx
  src/pages/index.ts
  src/routes/router.tsx
Labels: enhancement

#9 [Feat] ErrorPage 제작
  src/pages/ErrorPage.tsx
Labels: enhancement

#10 [Fix][Refactor] 타입 에러 해결 및 이슈 파싱 함수 유틸로 분리
  src/components/domain/issue/IssueList.tsx
  src/pages/DetailPage.tsx
  src/types/issue.ts
  src/utils/index.ts
  src/utils/parseIssue.ts
Labels: bug

#11 [Feat] 메인 페이지에 이슈 리스트 렌더, 이슈 아이템과 디테일 페이지 연결
  src/components/domain/issue/IssueList.tsx
  src/components/domain/issue/IssueListItem.tsx
  src/pages/MainPage.tsx
Labels: enhancement

#12 [Feat] Header 컴포넌트 제작 및 추가
  src/App.tsx
  src/components/common/Header.tsx
Labels: enhancement

#13 [Docs] README 작성
  README.md
Labels: documentation

#14 [!HOTFIX] Header 컴포넌트 경로 누락
  src/components/common/index.ts
Labels: bug

#15 [!HOTFIX] Advertisement 경로 삭제
  src/components/common/index.ts
Labels: bug
